--- Makefile	2018-05-21 21:27:59.794018472 +0100
+++ Makefile_new	2018-05-21 21:29:36.990336108 +0100
@@ -30,7 +30,7 @@
 	( cd source/d0_blind_id && ./configure --enable-static --disable-shared $(RIJNDAELDETECT_CONFIGURE) )
 	$(MAKE) -C source/d0_blind_id
 	$(MAKE) -C source/gmqcc
-	$(MAKE) -C source/qcsrc FTEQCC=$(CURDIR)/source/gmqcc/gmqcc
+	$(MAKE) -C source/qcsrc QCC=$(CURDIR)/source/gmqcc/gmqcc
 	$(MAKE) -C source/darkplaces sv-release DP_CRYPTO_STATIC_LIBDIR=$(CURDIR)/source/d0_blind_id/.libs
 	$(MAKE) -C source/darkplaces cl-release DP_CRYPTO_STATIC_LIBDIR=$(CURDIR)/source/d0_blind_id/.libs
 	$(MAKE) -C source/darkplaces sdl-release DP_CRYPTO_STATIC_LIBDIR=$(CURDIR)/source/d0_blind_id/.libs
